<?php

function css_writer_v($arr, $name = "style.css", $sprite_name, $padding = 0) {
	$i = 0;
	$str = "/* Generated by el famoso Elias for your plus grand plaisir */\n\n";
	foreach ($arr as $value) {
		if ($sprite_name !== $value && $value !== "sprite.png") {
			$str .= ".";
			$str .= get_img_name($value);
			$i++;
			if ($i < count($arr))
				$str .= ", ";
		}
	}
	$i = 0;
	$str .= "\n{\ndisplay: inline-block;\nbackground: url('png.png') no-repeat;
overflow: hidden;\ntext-indent: -9999px;\ntext-align: center;\n}\n\n";
	foreach ($arr as $value) {
		if ($sprite_name !== $value && $value !== "sprite.png") {
			$str .= "." . get_img_name($value) . "\n{\nbackground-position: -";
			$str .= $padding . "px -";
			$str .= $i . "px; width: ";
			$str .= getimagesize($value)[0] . "px; height: ";
			$str .= getimagesize($value)[1] . "px;\n}\n\n";
			$i += (getimagesize($value)[1] + $padding);
		}
	}
	file_put_contents($name, $str);
}
?>